services:
  redis:
    image : redis
  backend:
    image : backend-project
    ports:
      - 8080:8080
    environment:
      - REQUEST_ORIGIN=http://localhost:5001
      - REDIS_HOST=redis
      - POSTGRES_HOST=db_redmine
  frontend:
    image : frontend-project
    ports:
      - 5001:5001
  db:
    image: postgres:18
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: example
    container_name: db_redmine
