services:
  redis:
    image : redis
  backend:
    image : backend-project
    #ports:
    #  - 8080:8080
    environment:
      #- REQUEST_ORIGIN=http://localhost:5001
      - REDIS_HOST=redis
      - POSTGRES_HOST=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DATABASE=postgres
    depends_on:
      - db
  frontend:
    image : frontend-project
    #ports:
    #  - 5001:5001
    depends_on:
      - backend
  db:
    image: postgres:18
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./database:/var/lib/postgresql
  nginx:
    image: nginx
    ports:
    - 8000:80
    environment:
      - NGINX_PORT=80
    volumes:
    - ./nginx.conf:/etc/nginx/nginx.conf 
    depends_on:
    - frontend
    - backend

volumes:
  database:
